apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: ifc-converter-job
spec:
  # Keep ONE idle Job around at all times
  minReplicaCount: 0               # ⇒ “idle Job” invariant
  pollingInterval: 5               # seconds between Redis queries

  # Source of truth: your Redis list
  triggers:
  - metadata:
      address: ifcupload-redis-service.default.svc.cluster.local:6379
      listLength: "1"
      listName: ifc-export-task-queue
    type: redis

  # Template for each Job
  jobTargetRef:
    ttlSecondsAfterFinished: 5  # clean up after 10 min
    backoffLimit: 1                # retry once on failure
    template:
      metadata:
        labels: {app: ifc-converter-job}
      spec:
        restartPolicy: Never
        containers:
          - name:  ifc-converter-job
            image: ghcr.io/contextmachine/ifcexport2:master
            volumeMounts:
            - mountPath: /app/volume
              name: vol


            env:
            - name: REDIS_URL
              value: redis://ifcupload-redis-service.default.svc.cluster.local:6379/0
            - name: VOLUME_PATH
              value: /app/volume
            - name: BUCKET_PREFIX
              valueFrom:
                secretKeyRef:
                  key: BUCKET_PREFIX
                  name: ifcupload-secrets

            command: [ "python",  "ifcexport2/appv2/job.py" ]
            resources:               # generous but finite
              requests:
                cpu: "16"
                memory: 8Gi
            nodeSelector:
              workload: heavy-jobs
            restartPolicy: Never
            tolerations:
            - effect: NoSchedule
              key: workload
              operator: Equal
            value: heavy-jobs
        volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: ifcuploader-csi-s3-pvc-dynamic
            readOnly: false
