apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifcupload-celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifcupload-celery
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ifcupload-celery
    spec:
      containers:
        - name: ifcupload-celery
          image:  ghcr.io/contextmachine/ifcexport2:master  #
          imagePullPolicy: Always
          command: ["/opt/conda/bin/celery",
              "-A",
               "ifcexport2.tasks",
               "worker"]
          env:
            - name: REDIS_URL
              value: "redis://ifcupload-redis-service:6379/0"
            - name: VOLUME_PATH
              value: "/app/volume"
            - name: BUCKET_PREFIX
              value: "https://storage.yandexcloud.net/kube-cxm-cni/pvc-65a8b5f6-9fee-4d05-ab8e-07c2bc5fe695"
          volumeMounts:
            - mountPath: /app/volume
              name: vol
      restartPolicy: Always
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: ifcuploader-csi-s3-pvc-dynamic
            readOnly: false

