apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifcupload-celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifcupload-celery
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ifcupload-celery
    spec:
      containers:
        - name: ifcupload-celery
          image:  ghcr.io/contextmachine/ifcexport2:master  #
          imagePullPolicy: IfNotPresent
          command: ["/opt/conda/bin/celery",
                    "-A",
                    "ifcexport2.tasks",
                    "worker",
                    "--max-memory-per-child=5242880" # 5Gi
          ]
          env:
            - name: REDIS_URL
              value: "redis://ifcupload-redis-service:6379/0"
            - name: VOLUME_PATH
              value: "/app/volume"
              # kubectl create secret generic ifcupload-secrets --from-literal=BUCKET_PREFIX=https://my-secret-bucket-prefix
            - name: BUCKET_PREFIX
              valueFrom:
                secretKeyRef:
                  name: ifcupload-secrets
                  key: BUCKET_PREFIX
          volumeMounts:
            - mountPath: /app/volume
              name: vol
      restartPolicy: Always
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: ifcuploader-csi-s3-pvc-dynamic
            readOnly: false

