
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifcupload
  labels:
    app: ifcupload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifcupload
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: ifcupload
      labels:
        app: ifcupload
    spec:
      containers:
        - name: ifcupload-container
          image: ghcr.io/contextmachine/ifcexport2:master  # Ссылка на образ.
          imagePullPolicy: Always
          env:
          - name: VOLUME_PATH
            value: "/app/volume"
          - name: REDIS_URL
            value: "redis://ifcupload-redis-service:6379/0"


          command: ["/opt/conda/bin/python", "-m","ifcexport2.api.app"]
          volumeMounts:
            - mountPath: /app/volume
              name: vol

      restartPolicy: Always
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: ifcuploader-csi-s3-pvc-dynamic
            readOnly: false
