# PVC использующий S3 в качестве хранилища.
# В него должны быть загружены веса моделей ИИ использующихся в приложении.
# При таком подходе для обновления весов необходимо загрузить новые веса в S3
# и перезапустить приложение, убив всех подов.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ifcuploader-csi-s3-pvc-dynamic
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  storageClassName: csi-s3
