apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifcupload-redis
  labels:
    app: ifcupload-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifcupload-redis
  template:
    metadata:
      name: ifcupload-redis
      labels:
        app: ifcupload-redis
    spec:
      containers:
        - name: ifcupload-redis-container
          image: redis:latest  # Ссылка на образ.
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data # Persistent storage
              name: rds-data
      restartPolicy: Always
      volumes:
        - name: rds-data
          persistentVolumeClaim:
            claimName: ifcupload-redis-hdd-pvc
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: ifcupload-redis-service
spec:
  selector:
    app: ifcupload-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP