

apiVersion: v1
kind: Service
metadata:
  name: ifcupload
spec:
  selector:
    app: ifcupload
  ports:
    - name: http
      port: 8022
      protocol: TCP
      targetPort: 8022
  sessionAffinity: None
  type: ClusterIP
